version: '3.4'

services:
  quotes-web:
    image: ${DOCKER_REGISTRY-}quotesweb
    build:
      context: .
      dockerfile: quotes-web/Dockerfile
    volumes:
      - ${APPDATA}\Quotes\appsettings.json:/config.json
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "mysuperSecureSQlServerPassword152"
    #ports:
    #  - "1433:1433"