version: '3.4'

services:
  quotes-web:
    image: ${DOCKER_REGISTRY-}quotesweb
    build:
      context: .
      dockerfile: quotes-web/Dockerfile
    volumes:
      - ${APPDATA}\Quotes\appsettings.json:/config.json
