version: '3.8'

services:
  quotes-web:
    image: ${DOCKER_REGISTRY-}quotesweb
    build:
      context: .
      dockerfile: quotes-web/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}\Quotes\appsettings.json:/config.json
      - ${APPDATA}\Quotes\Images:/images
    depends_on:
      - "db"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "mysuperSecureSQlServerPassword152"
    ports:
      - "1433:1433"