name: Docker Image CI

on:  
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: src/quotes/quotes-web/Dockerfile
        context: ./src/quotes
        push: true
        tags: kifkof/quotes:${{ steps.version.outputs.version }}, kifkof/quotes:latest
